import './global.css';
import Providers from './providers';
import { Layout } from '../components/layout';
import { ReactNode } from 'react';
import { Crimson_Pro, Source_Code_Pro } from 'next/font/google';

// Next's font-loader compiler plugin requires the call be assigned to a
// module-scope const. Unused otherwise — self-hosted @font-face injection
// under the real Google font family name is referenced by literal name via
// --font-sans/--font-mono in global.css.
const _crimsonPro = Crimson_Pro({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
});
const _sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  weight: ['200', '400', '600', '700'],
});

export const metadata = {
  title: 'web',
  description: 'Generated by @dcat23/next-feature',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  )
}
