spring:
  profiles:
    include: seed-data
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
logging:
  level:
    root: info
    xyz:
      catuns:
        imp:
          api: debug
